spring:
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create
    showSql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5432/prettierhomes
    driverClassName: org.postgresql.Driver
    username: db_admin
    password: OOoqm+cQm+ilPOJfIpu/ROmZOVB8AnTMOHtsakzL9VA=



