
server:
  port: 8080
  error:
    #    include-stacktrace: never
    include-binding-errors: always
    include-message: always

spring:
  servlet:
    multipart:
      max-file-size: 3MB
      max-request-size: 30MB
  web:
    locale: auto
  messages:
    basename: messages
    encoding: UTF-8
    cache-duration: -1
    fallback-to-system-locale: true
  profiles:
    include:
      - security
      - data
      - mail
      - scheduler
  freemarker:
    template-loader-path: file:C:\Users\Bilal\IdeaProjects\prettierHome-backend\src\main\resources\templates

#ExportFilePath
export:
  folder:
    path:
      xls: ${user.home}/Desktop/.prettierReports

